name: Deploy

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-astro.yml@master
        with:
            domain: demos.codestar.ir
            base-href: /
        secrets: inherit
